server:
  port: 8095

#security:
#  oauth2:
#    client:
#      client-id: auth_id
#      client-secret: auth_secret
#    resource:
#      jwt:
#        key-value: jwt_secret_key

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 10000
      idleTimeout: 10000
      maximumPoolSize: 10
      minimumIdle: 5
      validation-timeout: 10000
    password: qwer1234
    url: jdbc:mariadb://localhost:13306/jpetstoredb
    username: jpetstore